favicon: /favicon.ico
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  icon: flag-cn
  name: Chinese

search: false

githubCorner: '<a href="https://github.com/nexmoe/bilibili-cc" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 高等数学
    icon: far fa-star
    config: AdvancedMathematics
  - name: 英语
    icon: far fa-star
    config: English
  - name: 法律
    icon: far fa-star
    config: Law
  - name: 摄影
    icon: far fa-star
    config: Photography
  - name: 计算机二级
    icon: far fa-star
    config: NationalComputerRankExamination
  - name: 书法
    icon: far fa-star
    config: Calligraphy
  - name: 软件
    icon: far fa-star
    config: Software
  - name: 平面设计
    icon: far fa-star
    config: GraphicDesign
  - name: 平面设计
    icon: far fa-star
    config: History

AdvancedMathematics:
  - name: 宋浩老师官方
    url: https://space.bilibili.com/66607740
    img: /images/logos/66607740.jpg
    description: 高等数学、线性代数、考研
  - name: 小元老师高数线代概率
    url: https://space.bilibili.com/74434623
    img: /images/logos/74434623.jpg
    description: 小元老师。提供高品质、形象、趣味、透彻的数学课程。
  - name: 高数叔的百宝箱
    url: https://space.bilibili.com/408433491
    img: /images/logos/408433491.jpg
    description: 

English:
  - name: A路人
    url: https://space.bilibili.com/391679
    img: /images/logos/391679.jpg
    description: 英语语法学习、《洋屁教室》系列视频，幽默搞笑英语UP主
  - name: 口语老炮儿马思瑞
    url: https://space.bilibili.com/24801003
    img: /images/logos/24801003.jpg
    description: 明星口语分析、中西文化差异、英语教学
  - name: 一起暴击口语
    url: https://space.bilibili.com/433248184
    img: /images/logos/433248184.jpg
    description: 用心教英语，认真做教育。
  - name: 英国小克里
    url: https://space.bilibili.com/37398761
    img: /images/logos/37398761.jpg
    description: 剑桥大学中文系，国际同声传译
  - name: FanfaniShare
    url: https://space.bilibili.com/346396741
    img: /images/logos/346396741.jpg
    description: 英语发音学习、在美国高校教英语的英语干货铺老板娘
  - name: 英语老师Lee
    url: https://space.bilibili.com/131058159
    img: /images/logos/131058159.jpg
    description: 英语发音学习、原美国薇诺娜高中英语教师，教授美国学生英语课程；原美国德拉塞尔语言学院学术写作教师。
  - name: Real麦克老师
    url: https://space.bilibili.com/19859602
    img: /images/logos/19859602.jpg
    description: 英语单词学习、有趣！有料！你的贴身外教！
  - name: 早安英文
    url: https://space.bilibili.com/35636660
    img: /images/logos/35636660.jpg
    description: 英语单词学习、学口语，就来早安英文！
  - name: 张富贵的英语世界
    url: https://space.bilibili.com/401727458
    img: /images/logos/401727458.jpg
    description: 英语单词学习、ZJUerPhD/大学英语老师
  - name: 圣诞节南瓜灯
    url: https://space.bilibili.com/319176130
    img: /images/logos/319176130.jpg
    description: CC字幕视频分享者，分享有价值的英语学习资源。
  - name: AJ传译君
    url: https://space.bilibili.com/27792668
    img: /images/logos/27792668.jpg
    description: CC字幕视频分享者，赋闲在家的同传

Software: 
  - name: doyoudo
    url: https://space.bilibili.com/20503549
    img: /images/logos/20503549.jpg
    description: PS 、AI 、AE 、PR 、AU 、Id 、C4D 、Final Cut Pro 、Snapseed
  - name: 老秦PPT
    url: https://space.bilibili.com/491456841
    img: /images/logos/491456841.jpg
    description: 源于PPT，不止PPT。
  - name: 拉小登Excel
    url: https://space.bilibili.com/400511102
    img: /images/logos/400511102.jpg
    description: 好的表格是设计出来的
  - name: oeasy
    url: https://space.bilibili.com/2884629
    img: /images/logos/2884629.jpg
    description: 你想学的软件这几乎都有
  - name: 星月兮
    url: https://space.bilibili.com/17638509
    img: /images/logos/17638509.jpg
    description: 
  - name: 我是于干
    url: https://space.bilibili.com/69743276
    img: /images/logos/69743276.jpg
    description: PS、AE、AU
  - name: 一周进步
    url: https://space.bilibili.com/308552985
    img: /images/logos/308552985.jpg
    description: 软件、网页、APP安利、各类软件教程，这个UP的平面设计不错

Law:
  - name: 罗翔说刑法
    url: https://space.bilibili.com/517327498
    img: /images/logos/517327498.jpg
    description: 厚大法考刑法独家授课老师

Photography:
  - name: 影视飓风
    url: https://space.bilibili.com/946974
    img: /images/logos/946974.jpg
    description: 器材评测、拍摄制作技巧
  - name: 庄子HD
    url: https://space.bilibili.com/361556391
    img: /images/logos/361556391.jpg
    description: 拍摄技巧、拍摄模仿
  - name: 视频大拍档
    url: https://space.bilibili.com/110974
    img: /images/logos/110974.jpg
    description: Vlog制作教程、剪辑视频、运镜、摄影手法。
  - name: 左手plus
    url: https://space.bilibili.com/20166755
    img: /images/logos/20166755.jpg
    description: 摄影知识、器材挑选、拍摄技巧
  - name: 二麦科技
    url: https://space.bilibili.com/86566982
    img: /images/logos/86566982.jpg
    description: 拍照、视频、创作过程、构图技巧
  - name: 深夜君-深夜摄影教室
    url: https://space.bilibili.com/57855066
    img: /images/logos/57855066.jpg
    description: 后期调色、摄影技巧、照片修图
    - name: 极地手记
    url: https://space.bilibili.com/6314588
    img: /images/logos/6314588.jpg
    description: Vlog 教学

NationalComputerRankExamination:
  - name: 小黑课堂计算机二级
    url: https://space.bilibili.com/48133212
    img: /images/logos/48133212.jpg
    description: 

Calligraphy: 
  - name: 一笔落尘
    url: https://space.bilibili.com/147071622
    img: /images/logos/147071622.jpg
    description: 用笔为浮躁的心带来一缕清流。b站的小伙伴们一起来练字吧！

GraphicDesign:
  - name: 优设基础训练营
    url: https://space.bilibili.com/39990344
    img: /images/logos/39990344.jpg
    description: 优设旗下教育机构
  - name: oooooohmygosh
    url: https://space.bilibili.com/38053181
    img: /images/logos/38053181.jpg
    description: 提高审美，适合所有人

History:
  - name: 御史房
    url: https://space.bilibili.com/34264408
    img: /images/logos/34264408.jpg
    description: 中国历史为、X分钟看懂历史事件、人物遭遇


#about:
#  url: https://sspai.com/post/39683
#  icon: far fa-heart
#  name: CC字幕是什么？

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>的demo站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: HCLonely
    url: https://blog.hclonely.com/
    img: /images/logos/myblog.png
    description: 懒人一个
    html: '<br /><blockquote><p>本站是<a href="https://github.com/HCLonely">HCLonely</a>基于<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>项目做的一款<a href="https://hexo.io/">Hexo</a>主题。</p></blockquote>'

since: 2021

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
